### ISSUE TITLE
Forced colors

### ISSUE THREAD

**Issue by EllyLoel** [ericwbailey/a11y-syntax-highlighting#6]
Just wondering whether the `-ms-high-contrast` media queries should be updated to `forced-colors`?

Seems like [Microsoft is recommending](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/#gist105426781:~:text=Differences%20from%20legacy%20implementations) this:
```css
@media (-ms-high-contrast: active), (forced-colors: active) {}
```
Along with using the new system colors, I assume something like this would work for fallback (though I haven't tested it):
```css
color: WindowText;
color: CanvasText;
```

**Comment by EllyLoel** [comment]
This is a quick and dirty update of the high contrast mode style to include forced colors following the idea above (again haven't yet had the chance to test that this actually works): 
```css
@media (-ms-high-contrast: active), (forced-colors: active) {
  code[class*="language-"],
  pre[class*="language-"] {
    color: WindowText;
    color: CanvasText;
    background: Window;
    background: Canvas;
  }

  :not(pre) > code[class*="language-"],
  pre[class*="language-"] {
    background: Window;
    background: Canvas;
  }

  .token.important {
    background: Highlight;
    color: Window;
    color: Canvas;
    font-weight: normal;
  }

  .token.atrule,
  .token.attr-value,
  .token.function,
  .token.keyword,
  .token.operator,
  .token.selector {
    font-weight: bold;
  }

  .token.attr-value,
  .token.comment,
  .token.doctype,
  .token.function,
  .token.keyword,
  .token.operator,
  .token.property,
  .token.string {
    color: Highlight;
  }

  .token.attr-value,
  .token.url {
    font-weight: normal;
  }
}
```
